# Generated by Django 5.0.3 on 2024-04-02 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cup',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='plate',
            old_name='name',
            new_name='title',
        ),
    ]
