# Generated by Django 5.0.3 on 2024-04-02 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_name_cup_title_rename_name_plate_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cup',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='quantity',
        ),
    ]
